/* DO NOT EDIT THIS FILE - it is machine generated */

#ifndef __cgrb_eta_server_Login__
#define __cgrb_eta_server_Login__

#include <jni.h>

#ifdef __cplusplus
extern "C"
{
#endif

JNIEXPORT jint JNICALL Java_cgrb_eta_server_Login_login (JNIEnv *env, jclass, jstring, jstring);
JNIEXPORT jint JNICALL Java_cgrb_eta_server_Login_startUserService (JNIEnv *env, jclass, jstring, jstring, jstring);
JNIEXPORT jint JNICALL Java_cgrb_eta_server_Login_changePassword (JNIEnv *env, jclass, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif

#endif /* __cgrb_eta_server_Login__ */
